name: Publish nightly docker release
# Builds the precice/precice:nightly image
on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        default: develop
  workflow_call:
    inputs:
      branch:
        type: string
        default: develop
  schedule:
    - cron: '0 3 * * *'

jobs:
  dockerfile:
    name: "Build precice:nightly"
    runs-on: ubuntu-latest
    env:
        docker_username: precice
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.docker_username }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Dockerfile
        uses: docker/build-push-action@v6
        with:
          push: true
          file: "./tools/releasing/packaging/docker/nightly.dockerfile"
          tags: ${{ env.docker_username }}/precice:nightly
          build-args: |
            BRANCH=${{ github.event.inputs.branch || 'develop' }}
