name: Test
on:
  workflow_dispatch:
    inputs:
      version:
        type: string

jobs:

  docker-release:
    name: "Release Dockerfile"
    uses: ./.github/workflows/publish-docker-release.yml
    with:
      version: ${{ github.event.inputs.version }}
      latest: true
    secrets: inherit

  docker-nightly:
    name: "Release Nightly"
    uses: ./.github/workflows/publish-docker-nightly.yml
    with:
      branch: ${{ github.event.inputs.version }}
    secrets: inherit
